export const categories = [
  "Adventure",
  "Art",
  "Children’s",
  "Contemporary",
  "Cookbook",
  "Dystopian",
  "Families & Relationships",
  "Fantasy",
  "Health",
  "Historical fiction",
  "History",
  "Horror",
  "Humor",
  "Memoir",
  "Motivational",
  "Mystery",
  "Paranormal",
  "Personal Development",
  "Romance",
  "Science Fiction",
  "Self-help",
  "Thriller",
  "Travel",
  "Guide / How-to",
];
